### ISSUE TITLE
more resources

### ISSUE THREAD

**Issue by timoxley** [stoeffel/awesome-fp-js#1]
Some of these are a little old now but I have a similar list over here, if you'd like to steal anything or perhaps even add this to it.

https://github.com/timoxley/functional-javascript-workshop/wiki

**Comment by stoeffel** [comment]
Nice. thanks I will add your repo and maybe add some links directly. Feel free to make a pr if you like.

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
I added your workshop and will probably add some of the resources later. Closed in https://github.com/stoeffel/awesome-fp-js/commit/8e32fbfcf4def8a74fbbac9218899fc4f72e1163

Thanks for pointing me to this.
