### ISSUE TITLE
make this list compliant with awesome

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/awesome-fp-js#10]
https://github.com/sindresorhus/awesome
add badge contributing.md ....
then add it to awesome

**Comment by stoeffel** [comment]
https://github.com/sindresorhus/awesome/blob/master/awesome.md

**Comment by stoeffel** [comment]
@naehrstoff what do you think? Is it ready to go on the awesome list?

**Comment by jwoudenberg** [comment]
Looks very nice! Bookmarked some new links just going through it again :).

**Comment by jwoudenberg** [comment]
Oop, sorry about that...

**Comment by naehrstoff** [comment]
The thing I would still like to do most is to go through the articles to make sure they're solid. From these articles, I would then like to put the best one for beginners at the top so people can get a solid start into the topic. Also, I was thinking of watching Christian Johansen's videos again to decide which one to pick for the list.

Something I would like you to do if you have the time is to have a look at is the list of people that I added: maybe you have some more, maybe we want to throw some out. I like to read all of them, but not all of them really write about FP JS on Twitter, so I'm not sure we should keep them. I tried to balance the list with regards to gender as much as I could, but if you know more women in FP JS, please add them.

So, even though my perfectionist brain would like to continue to refine all aspects of this list, I don't think that these two tasks are blocking us from publishing the list to the Awesome repo. And the selection of the most awesome libraries will also have to be done together with the community, so I think we have a good starting point that we'll be able to refine in the future.

**Comment by stoeffel** [comment]
Will have a look at the who to follow list as soon as possible (I think I have some additions). and will create a PR to awesome soonish.

**Comment by naehrstoff** [comment]
Closing because pull request to Awesome List has been accepted.
