### ISSUE TITLE
Connect with/add to other similar lists

### ISSUE THREAD

**Issue by naehrstoff** [stoeffel/awesome-fp-js#12]
Note to future self:

* There's a similar list to ours over here: https://github.com/busypeoples/functional-programming-javascript We could connect with the author.
* The above repo is mentioned in this list: https://github.com/lucasviola/awesome-functional-programming#repos We could ask them to add our repo as well.

**Comment by stoeffel** [comment]
SGTM
cc @lucasviola @busypeoplea
