### ISSUE TITLE
Question for submitting

### ISSUE THREAD

**Issue by Swizz** [stoeffel/awesome-fp-js#25]
Hi there !

I wanted to submit another thing for learning FP but, that raised few questions in my mind.

So, It is a series of articles on Medium written by `Charles Scalfani` (@cscalfani).
This series is called :  `So You Want to be a Functional Programmer`. Articles seem to be released weekly.

So, I think this is a great entry point, and need to break the guidelines for contributing, and be placed at the top of the resource list.

Another question, is, where to place it ? In articles ? In books ?
And what formalism ? Just the first article because cscalfani put link on each others to navigate in series.
Or do we need to put each link in the same line ?

> - [So You Want to be a Functional Programmer](https://medium.com/@cscalfani/so-you-want-to-be-a-functional-programmer-part-1-1f15e387e536) [#2](https://medium.com/@cscalfani/so-you-want-to-be-a-functional-programmer-part-2-7005682cec4a) [#3](https://medium.com/@cscalfani/so-you-want-to-be-a-functional-programmer-part-3-1b0fd14eb1a7) [#4](https://medium.com/@cscalfani/so-you-want-to-be-a-functional-programmer-part-4-18fbe3ea9e49) - Easy to understand with some examples introduction to Functional Programming in Javascript and Elm.

Cheers,

**Comment by stoeffel** [comment]
hey
thanks for contributing.
I think I would prefer a link to just the first article of the series.
additionally, I think that a "getting into fp js" section could be helpful.

**Comment by Swizz** [comment]
Yes, highlight beginners resources look really good to me.

**Comment by mikeaustin** [comment]
I love the list! It's curated, so it's the best of the best, but how do I find the "right" library? For example, I'm looking for a lightweight library with curry, flip, compose, identity, etc. to pair with immutable.js. Ramda seems big and complex. Maybe Crocks? I'm not necessarily asking, I'm just giving an example of how I use the list.
