### ISSUE TITLE
Consider adding Reactive Extensions tutorial

### ISSUE THREAD

**Issue by kanglicheng** [stoeffel/awesome-fp-js#54]
I found http://reactivex.io/learnrx/ to be a great resource for learning basic FP using JS. It's a series of interactive tasks that can be done in the browser and is the preparation for using Microsoft's Reactive extensions (Rx). Covers 5 basic higher order functions (HoFs) map, filter, reduce, concatAll, and zip.

**Comment by grossbart** [comment]
Thanks, I added these to our list. It is about Rx, but I also learned a lot from these exercises a while back and I think they are a good addition to our list.
