### ISSUE TITLE
Slack Channel invite

### ISSUE THREAD

**Issue by EricHenry** [stoeffel/awesome-fp-js#55]
Is there a way to get an invite to the slack channel?

**Comment by grossbart** [comment]
Hmmm, is it not as easy as signing up here?

https://functionalprogramming.slack.com/?redir=%2Fmessages%2Ffsharp

If it isn't, does this work:

https://fpchat-invite.herokuapp.com/

If you get it working, let us know how you did it so we can update the readme. I think I joined through a Twitter link a long while back.

**Comment by EricHenry** [comment]
The invite link worked!

The first link and the link in the readme took me to a slack portal that asked me to sign into the channel, but I couldn't because I wasn't a member.

**Comment by grossbart** [comment]
Thanks for your feedback! I changed the link to point to the invite form so others can join more easily.

**Comment by peterodigie** [comment]
Last day of 2022; not able to sign up here:

https://functionalprogramming.slack.com/

it is for members only.

plz can I get an invite?

**Comment by mathiasmaerker** [comment]
Would love to join as well, both Links don't work anymore
